import {
  PROJECT_LEVEL_ROUTES,
  ROUTE_NAMES,
  isRouteName,
  type Route,
  type RouteName
} from './nav'

/**
 * The identity of a tab, as a string BOTH main and the renderer derive the same
 * way.
 *
 * Two clicks that arrive at the same page must produce the same key or the user
 * gets two tabs showing one thing; two clicks that arrive at different pages must
 * not, or one reading silently replaces another. Since main owns the tab model
 * and the renderer paints it, "the same way" has to mean one function, not two
 * implementations that agree today.
 *
 * | route | key |
 * |---|---|
 * | paper, with a work | `paper:{projectId}:{workId}` |
 * | paper, no work yet | `paper:{projectId}:new` |
 * | every other project-scoped route | `{name}:{projectId}` |
 * | projects, schemas | `{name}` |
 *
 * **`projectId` is in EVERY project-scoped key, paper included.** A paper's
 * project-specific interpretation — relevance, expansion priority, inclusion
 * status, the user's overrides — lives in `project_work`, and the paper screen
 * queries its analyses, its ranking and its summaries per project. The same paper
 * open in two projects is two different pages, and one key for both would show
 * the reader one project's judgement under the other project's heading.
 *
 * `evidenceId`, `quote`, `rowKey`, `schemaId` and `factId` are deliberately
 * ABSENT: they say where to look WITHIN a page, not which page it is. Following
 * "evidence →" twice at two different quotes must move within one tab.
 */

/** An id, as it may appear in a key: a bounded run of digits. */
const ID = '[0-9]{1,12}'

/**
 * The suffix that distinguishes a DELIBERATE duplicate of a page.
 *
 * Ctrl-click asks for a second tab on the page a tab already shows, but two tabs
 * may not share a key or every op would address both. The suffix is an occurrence
 * number, generated by the model — never free text — and bounded so a loop cannot
 * mint unbounded key lengths.
 *
 * Part of the SHARED pattern rather than of the model's private vocabulary,
 * because main recovers a route from a key when it re-homes a crashed window's
 * tabs and when it restores a session. A key the model can emit but this module
 * cannot read is a page that silently fails to come back.
 */
const DUP = '(?:#[0-9]{1,3})?'
/** The largest duplicate index a key may carry, from `DUP`'s three digits. */
export const MAX_TAB_DUPLICATES = 999

/**
 * The shape main validates an incoming key against, before it is allowed to
 * address anything.
 *
 * Anchored at both ends and admitting only the route names this build knows,
 * each with the EXACT arity its rule gives it, so a key can never be free text:
 * no whitespace, no path traversal, no SQL, no newline, and no
 * plausible-looking-but-wrong shape like a bare `paper` or a `graph:3:7`. Built
 * from `ROUTE_NAMES` rather than written out, so adding a route cannot leave the
 * validator and the generator disagreeing.
 *
 * Ids are bounded at 12 digits because an id is a SQLite rowid; an unbounded
 * `[0-9]+` would accept a megabyte of digits.
 */
export const TAB_KEY_PATTERN = new RegExp(
  '^(?:' +
    [
      // projects | schemas
      `(?:${[...PROJECT_LEVEL_ROUTES].join('|')})`,
      // paper:{project}:{work|new}
      `paper:${ID}:(?:${ID}|new)`,
      // everything else: {name}:{project}
      `(?:${ROUTE_NAMES.filter((n) => n !== 'paper' && !PROJECT_LEVEL_ROUTES.has(n)).join(
        '|'
      )}):${ID}`
    ].join('|') +
    ')' +
    DUP +
    '$'
)

/** The most characters a key may occupy, as a second, cruder bound. */
export const TAB_KEY_MAX = 64

function requireProjectId(name: RouteName, projectId: number | null): number {
  if (projectId === null || !Number.isSafeInteger(projectId) || projectId < 0) {
    throw new Error(
      `route "${name}" is project-scoped and needs a project id, got ${String(projectId)}`
    )
  }
  return projectId
}

/** The tab `route` opened in `projectId` belongs to. */
export function tabKey(route: Route, projectId: number | null): string {
  if (!isRouteName(route.name)) throw new Error(`unknown route "${String(route.name)}"`)
  // An app-level route is a singleton: it shows the same thing whichever project
  // the sidebar happens to have open, so including the project would fork the tab
  // every time the user switched projects and left the copies behind.
  if (PROJECT_LEVEL_ROUTES.has(route.name)) return route.name
  const pid = requireProjectId(route.name, projectId)
  if (route.name !== 'paper') return `${route.name}:${pid}`
  const { workId } = route
  if (workId === undefined || workId === null) {
    // ONE such tab per project, not per click: an unselected paper page is a
    // single place the user can be, and the alternative is an unbounded number of
    // identical empty tabs.
    return `paper:${pid}:new`
  }
  if (!Number.isSafeInteger(workId) || workId < 0) {
    throw new Error(`paper route needs a work id, got ${String(workId)}`)
  }
  return `paper:${pid}:${workId}`
}

/** A key decomposed back into the navigation state it names. */
export interface ParsedTabKey {
  name: RouteName
  projectId: number | null
  workId: number | null
  route: Route
  /**
   * Which deliberate duplicate of this page the key names: 1 for the original.
   *
   * Kept out of `route` — it is not part of where the page IS, only of which copy
   * of it this tab is — so `tabKey(parsed.route, parsed.projectId)` still yields
   * the base key and `duplicateKey` reconstructs the suffixed one.
   */
  duplicate: number
}

/**
 * The key for the `n`th deliberate copy of a page. `n === 1` is the base key.
 *
 * The one place the suffix is written, so the model, the validator and the parser
 * cannot drift.
 */
export function duplicateKey(base: string, n: number): string {
  if (!Number.isSafeInteger(n) || n < 1 || n > MAX_TAB_DUPLICATES) {
    throw new Error(`duplicate index out of range: ${String(n)}`)
  }
  return n === 1 ? base : `${base}#${n}`
}

/**
 * Read a key back, or `null` if it is not one this module could have produced.
 *
 * Never throws, because every caller is handling a value that came from outside:
 * an IPC argument, a restored session file, a drag payload. `tabKey(parsed)` is
 * the identity on anything this returns, which is what lets main hold keys as the
 * canonical form and still recover the route to hand a new window.
 */
export function parseTabKey(key: string): ParsedTabKey | null {
  if (typeof key !== 'string' || key.length === 0 || key.length > TAB_KEY_MAX) return null
  if (!TAB_KEY_PATTERN.test(key)) return null
  // The duplicate suffix is split off FIRST, so everything below reasons about the
  // page rather than about which copy of it this is.
  const hash = key.indexOf('#')
  const duplicate = hash < 0 ? 1 : Number(key.slice(hash + 1))
  if (!Number.isSafeInteger(duplicate) || duplicate < 1) return null
  const parts = (hash < 0 ? key : key.slice(0, hash)).split(':')
  const name = parts[0]
  if (!isRouteName(name)) return null

  if (PROJECT_LEVEL_ROUTES.has(name)) {
    // An app-level key carries nothing else. A trailing segment means whoever
    // built it was working from a different rule than this one.
    if (parts.length !== 1) return null
    return { name, projectId: null, workId: null, route: { name } as Route, duplicate }
  }

  if (name === 'paper') {
    if (parts.length !== 3) return null
    const projectId = Number(parts[1])
    if (!Number.isSafeInteger(projectId)) return null
    if (parts[2] === 'new') {
      return { name, projectId, workId: null, route: { name: 'paper' }, duplicate }
    }
    const workId = Number(parts[2])
    if (!Number.isSafeInteger(workId)) return null
    return { name, projectId, workId, route: { name: 'paper', workId }, duplicate }
  }

  if (parts.length !== 2) return null
  const projectId = Number(parts[1])
  if (!Number.isSafeInteger(projectId)) return null
  return { name, projectId, workId: null, route: { name } as Route, duplicate }
}

/** Would these two navigations land in the same tab? */
export function isSameTarget(
  a: Route,
  aProjectId: number | null,
  b: Route,
  bProjectId: number | null
): boolean {
  return tabKey(a, aProjectId) === tabKey(b, bProjectId)
}
