import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import type {
  DocumentDTO,
  ReviewItemDTO,
  AnalysisRunDTO,
  ExtractionRowDTO,
  ExtractionSchemaDTO,
  FactDTO,
  FactVerdictKind
} from '@shared/contract'
import { useAsync } from '../lib/useAsync'
import { DataView, EmptyState, ErrorState, SkeletonRows } from '../components/States'
import { PdfDocView, type PdfHighlight } from '../components/PdfDocView'
import { groupReadings, readingKey, type WorkReadings } from '../lib/readings'
import { fmtTime } from '../lib/format'
import { RichText } from '../components/RichText'

/**
 * REVIEW — per PAPER, in the paper's own table.
 *
 * WHY PER-PAPER. The queue escalates individual FACTS, but a fact is one cell of
 * one reading of one paper's extraction table, and a cell is not judgeable on
 * its own: `27` is a different question when every neighbouring reading says 25
 * than when it stands alone. Reviewing paper by paper means the table is drawn
 * ONCE and stays put while the reviewer works through its flagged cells, instead
 * of re-rendering the same context under every item.
 *
 * The unit of DECISION is still the fact — `recordFactVerdict` writes one row
 * per fact — so nothing about the data model is bent to the grouping.
 *
 * WHAT IS SHOWN, AND WHY THAT AND NOT MORE:
 *   the paper's table   — from `getExtractionRows` + `listSchemas`, grouped by
 *                         the SHARED `groupReadings` so a reading here is the
 *                         same reading the Extraction matrix and the Paper
 *                         sidebar show. Flagged cells are the only targets.
 *   the crop            — THE SAME IMAGE THE MODEL WAS SHOWN. `renderTableCrops`
 *                         is called by the extractor and by the record reviewer
 *                         alike, precisely because (its own header) "a reviewer
 *                         handed only the flattened text is asked to find a
 *                         fault in the one artefact where the fault is
 *                         invisible" — the text layer stores `0 . 29 6 0 . 11`
 *                         for `0.29 ± 0.11`.
 *   the text            — folded. It is what the model actually READ, so when it
 *                         and the crop disagree that difference IS the finding.
 *   the failed check    — folded, and only when there is one.
 *
 * `ReviewItemDTO` carries no subject, no field and no evidence, so the cell a
 * fact belongs to is resolved by matching `fact_id` against `getExtractionRows`,
 * and its quote by finding the fact inside `getWorkAnalyses`.
 */

// ---------------------------------------------------------------- verdicts
const VERDICT: Record<FactVerdictKind, { past: string; cls: string }> = {
  accepted: { past: 'Kept', cls: 'kept' },
  corrected: { past: 'Changed', cls: 'changed' },
  rejected: { past: 'Struck', cls: 'struck' },
  // A retraction is recorded but never READ back as a verdict: `getReviewQueue`
  // maps `unresolved` to `verdict: null`, so the item simply returns to the
  // queue. Kept because FactVerdictKind requires it.
  unresolved: { past: 'Undone', cls: '' }
}

/**
 * The margin note: the shortest TRUE sentence about why this row is here.
 *
 * Derived only from `ReviewItemDTO` fields, in the EXACT precedence
 * `getReviewQueue` uses to compose `reason` (repositories.ts) — so the note and
 * the reason printed beneath it can never state two different things. No glyph:
 * a `~` or `≈` beside a number is a symbol the reader would have to be taught,
 * and nothing on this screen teaches it.
 */
function noteFor(it: ReviewItemDTO): string {
  if (it.failed_checks.length > 0) return 'A check disagreed'
  if (it.kind === 'uncertain-conflicting') return 'The model was unsure'
  if (it.verifier_result === 'failed') return "The model's answer was malformed"
  if (it.verifier_result === 'partial') return 'Part of the answer was malformed'
  if (it.kind === 'inferred') return 'Not stated — worked out'
  return 'Picked at random to check'
}

// ---------------------------------------------------------------- the crop
/**
 * The table picture the model was given, for the paper being reviewed.
 *
 * Rendered on demand from the PDF rather than stored, so what the reviewer sees
 * is regenerated by the same code path the extractor used — not a lookalike.
 * A paper whose values came from prose has NO crop, and that is not the same as
 * a paper whose tables could not be rendered; `getTableCrops` reports which.
 */
/**
 * The PAPER ITSELF, at the passage the value was read from.
 *
 * NOT a rendered picture. A page rasterised at `MAX_EDGE_PX` is sized for a
 * vision model — an A4 page is ~842pt tall, so a full page comes back at barely
 * above native resolution and reads as a blurry photograph of a document. The
 * app already renders PDFs properly: `PdfDocView` draws through pdf.js at a real
 * scale, keeps a selectable text layer, and anchors a highlight by the same
 * canonical index this quote was located with. So the reviewer gets the actual
 * page, sharp, and the highlight comes from the component that owns highlighting.
 */
function PassageView({
  workId,
  quote,
  pages
}: {
  workId: number
  quote: string | null
  /** The page(s) the wording sits on — the rest of the paper is not evidence. */
  pages: number[]
}): JSX.Element {
  const docs = useAsync<DocumentDTO[]>(() => window.api.getWorkDocuments(workId), [workId])
  const scrollRef = useRef<HTMLDivElement>(null)
  const [anchored, setAnchored] = useState<Set<string>>(new Set())

  /* PdfDocView scrolls to `active` itself — it polls for the band, and handles a
     span whose bands land on several pages by taking the first in document
     order. A hand-rolled scroll here measured a rect the viewer had not finished
     placing and left the passage just off screen. */
  const doc = useMemo(() => {
    const list = docs.data ?? []
    return (
      list.find((d) => d.is_preferred && d.content_status === 'fulltext') ??
      list.find((d) => d.content_status === 'fulltext') ??
      list[0] ??
      null
    )
  }, [docs.data])

  const highlights = useMemo<PdfHighlight[]>(
    () =>
      quote?.trim()
        ? [
            {
              annId: 'q',
              text: quote,
              // NOT `high`: that is the danger red the viewer reserves for a
              // real fault, and at 36% it swallows the text underneath. This
              // passage is not a problem — it is where the value came from — so
              // it takes the accent, tinted lightly enough to read through.
              severity: 'info',
              domain: 'issue',
              color: 'var(--accent)',
              // A short quote like `27 u C` canonicalises to four characters,
              // which occurs many times in a paper — the locator would anchor
              // the first one, on whatever page that is. Only the pages holding
              // the passage are rendered, so the search space is already the
              // right one; `frac` then puts the expected position at the middle
              // of that space rather than the whole document.
              //
              // NOT `scopeText`, which is how the Paper screen solves the same
              // shortness problem. That needs the evidence span's paragraph, and
              // this passage arrives through TableCropsDTO, which carries the
              // quote and its pages and no paragraph at all. Rendering two pages
              // instead of twenty-two is the same narrowing by other means.
              minMatch: 4,
              frac: 0.5
            }
          ]
        : [],
    [quote]
  )

  if (docs.loading) return <div className="rv-crop-none mono">opening the paper…</div>
  if (!doc) {
    return (
      <div className="rv-crop-none" data-testid="review-passage-none">
        This paper has no document on this computer, so the passage cannot be shown.
      </div>
    )
  }
  return (
    <>
      <div className="rv-crop-bar">
        <span className="mono rv-crop-what">where the model read it</span>
        {/* Anchoring is REPORTED, not assumed: a quote the viewer could not
            place must not leave the reader believing the page is scrolled to it. */}
        {highlights.length > 0 && anchored.size === 0 && (
          <span className="mono rv-crop-miss">not found on the page</span>
        )}
      </div>
      {/* NO scroller of our own. PdfDocView renders its own `.pdf-scroll` and
          attaches `scrollRef` to THAT — a wrapper with `overflow:auto` around it
          became a second scroller, so the viewer scrolled its inner element to
          the highlight while the outer one, the one actually clipping the view,
          never moved. This box only bounds the height.
          `active` is set unconditionally because the viewer's scroll effect
          polls for the band itself. */}
      <div className="rv-passage">
        <PdfDocView
          key={`${doc.id}-${pages.join(',')}`}
          documentId={doc.id}
          scrollRef={scrollRef}
          pages={pages}
          scale={2}
          highlights={highlights}
          active="q"
          onAnchoredIds={setAnchored}
        />
      </div>
    </>
  )
}

function CropView({
  workId,
  value,
  quote
}: {
  workId: number
  value: string | null
  quote: string | null
}): JSX.Element {
  const crops = useAsync(() => window.api.getTableCrops({ workId, quote }), [workId, quote])
  const [i, setI] = useState(0)
  /**
   * Bring the mark into view the moment its picture appears.
   *
   * A full page is far taller than the frame, so the passage the reviewer was
   * sent here to read routinely rendered below the fold — the highlight existed
   * and could not be seen, which is the same as not having one. Waited for from
   * the IMAGE's load event rather than a timer: before the bitmap has laid out
   * the mark's percentage offsets resolve against a zero-height box.
   */
  const stageRef = useRef<HTMLDivElement>(null)
  const centreOnMark = useCallback(() => {
    const stage = stageRef.current
    const box = stage?.parentElement
    const mark = stage?.querySelector<HTMLElement>('.rv-mark')
    if (!stage || !box || !mark) return
    box.scrollTop = Math.max(0, mark.offsetTop - (box.clientHeight - mark.offsetHeight) / 2)
    box.scrollLeft = Math.max(0, mark.offsetLeft - (box.clientWidth - mark.offsetWidth) / 2)
  }, [])

  useEffect(() => setI(0), [workId, quote])
  // A cached image fires no `load`, so switching tables would otherwise leave
  // the new picture scrolled wherever the last one was. Declared HERE, with the
  // other hooks: below the early returns it would run conditionally, which is
  // the hooks-order violation that blanked this screen.
  useEffect(() => {
    const id = requestAnimationFrame(centreOnMark)
    return () => cancelAnimationFrame(id)
  }, [i, crops.data, centreOnMark])

  if (crops.loading) return <div className="rv-crop-none mono">rendering the page…</div>
  if (crops.error || !crops.data) {
    return (
      <div className="rv-crop-none">
        The page could not be rendered here. Open the paper to check this value.
      </div>
    )
  }
  const { images, found, unavailable, quotePages } = crops.data
  if (images.length === 0) {
    if (quote?.trim()) return <PassageView workId={workId} quote={quote} pages={quotePages} />
    return (
      <div className="rv-crop-none" data-testid="review-crop-none">
        {/* `found === 0` also covers a paper with NO PDF and one with no page
            geometry, so "it was read from the text" would be a provenance claim
            the data does not support. Say only what is known. And never print
            `unavailable` — it is a raw exception message. */}
        {found === 0
          ? 'No table was found on this paper, so there is no picture to check this value against.'
          : `This paper's ${found === 1 ? 'table' : 'tables'} could not be pictured, so there is nothing to check this value against here.`}
      </div>
    )
  }
  /**
   * ONLY the tables the cited wording was actually found on.
   *
   * `renderTableCrops` returns every table in the paper — up to four — because
   * the EXTRACTOR needs them all to read from. A reviewer checking one value
   * does not: a second table with nothing marked on it asks "why am I looking at
   * this?", and the honest answer is that we had no reason to show it. When the
   * wording matched nowhere, every table is kept — then the reader genuinely
   * does have to look, and hiding them would leave nothing to look at.
   */
  const marked = images.filter((c) => c.marks.length > 0)
  // No crop carries the wording: it was read off the TEXT LAYER, so the paper
  // itself is shown instead of tables that mark nothing.
  if (quote?.trim() && marked.length === 0)
    return <PassageView workId={workId} quote={quote} pages={quotePages} />
  const shown = marked
  const img = shown[Math.min(i, shown.length - 1)]
  // NO QUOTE AT ALL — the fact carries no evidence span, so nothing can be
  // marked and `marked` is empty. Reached without the guard above (which needs a
  // quote to have something to look for), this indexed an empty array and the
  // screen crashed on `img.label`. It is a real state: 39 of the corpus's facts
  // have no span.
  if (!img) {
    return (
      <div className="rv-crop-none" data-testid="review-crop-noquote">
        No wording was stored for this value, so there is nothing to show it
        against. Open the paper to check it.
      </div>
    )
  }
  return (
    <>
      <div className="rv-crop-bar">
        {/* A page means the value was read off the TEXT LAYER, not a table
            picture — the label says which artefact is on screen rather than
            claiming the same provenance for both. */}
        <span className="mono rv-crop-what">
          {img.label?.startsWith('Page ') ? 'where the model read it' : 'what the model was shown'}
        </span>
        {/* Tabs NAME their table. A row of bare `1 2 3` asks the reviewer to
            click through and remember which was which; the label and page are
            already on every crop, so the tab can simply say so. */}
        {shown.length > 1 && (
          <span className="rv-crop-tabs" role="tablist" aria-label="Tables from this paper">
            {shown.map((c, n) => (
              <button
                key={n}
                type="button"
                role="tab"
                className={`rv-crop-tab ${n === i ? 'is-on' : ''}`}
                onClick={() => setI(n)}
                aria-selected={n === i}
              >
                {c.label ?? 'Table'} <u className="mono">p.{c.page}</u>
              </button>
            ))}
          </span>
        )}
      </div>
      {/* The cited wording is marked ON the picture, positioned from the run
          geometry main resolved — never an eyeballed rectangle. The marks are
          drawn as an OVERLAY rather than burnt into the PNG, so the image the
          model was given stays byte-identical to what it was given, and hovering
          says whose annotation it is. */}
      <div className="rv-crop" data-testid="review-crop">
        <div className="rv-crop-stage" ref={stageRef}>
          <img
            src={`data:image/png;base64,${img.png}`}
            alt={img.caption ?? 'passage from the paper'}
            onLoad={centreOnMark}
          />
          {img.marks.map((m, n) => (
            <span
              key={n}
              className="rv-mark"
              style={{
                left: `${(m.x / img.widthPx) * 100}%`,
                top: `${(m.y / img.heightPx) * 100}%`,
                width: `${(m.w / img.widthPx) * 100}%`,
                height: `${(m.h / img.heightPx) * 100}%`
              }}
              data-tip="The part of the text the model used to support this finding."
            />
          ))}
        </div>
      </div>
      <div className="rv-crop-read">
        <span className="mono">read as</span>
        <strong>{value ?? 'no value'}</strong>
      </div>
    </>
  )
}

// ---------------------------------------------------------------- one paper
type Flagged = { item: ReviewItemDTO; fieldId: number | null; key: string | null }

function PaperReview({
  work,
  schema,
  flags,
  projectId,
  onOpenWork,
  onDecided
}: {
  work: WorkReadings
  schema: ExtractionSchemaDTO | null
  flags: Flagged[]
  projectId: number
  onOpenWork: (id: number) => void
  onDecided: () => void
}): JSX.Element {
  const [selected, setSelected] = useState<number | null>(null)
  const [showAll, setShowAll] = useState(false)
  const [correcting, setCorrecting] = useState(false)
  const [draft, setDraft] = useState('')
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const pending = useMemo(() => flags.filter((f) => f.item.verdict === null), [flags])
  const current =
    flags.find((f) => f.item.fact_id === selected) ?? pending[0] ?? flags[0] ?? null

  const paperWide = useMemo(() => {
    const m = new Map<number, ExtractionRowDTO>()
    for (const fid of work.paperLevel) {
      const only = work.cells.get(fid)
      if (only && only.size === 1) m.set(fid, [...only.values()][0])
    }
    return m
  }, [work])

  /**
   * Every flagged cell DISPLAYED on the same row as the current one.
   *
   * Not simply "same reading key": a paper-wide condition keeps the key of the
   * hidden reading it arrived on, so grouping by key alone left it in a group of
   * its own and the switcher never appeared for it. A flag is on this row if it
   * shares the row's key OR fills one of the row's paper-wide cells.
   */
  const siblings = useMemo(() => {
    if (!current) return []
    const wideFieldIds = new Set(paperWide.keys())
    const rowKey = wideFieldIds.has(current.fieldId ?? -1) ? null : current.key
    return flags.filter((f) => {
      if (wideFieldIds.has(f.fieldId ?? -1)) return true
      return rowKey !== null && f.key === rowKey
    })
  }, [flags, current, paperWide])

  // The quote lives on the owning RUN, not on the queue item, so it needs a
  // second read. Fetched per paper (not per fact) because one paper's runs
  // cover every fact in its table.
  const runs = useAsync<AnalysisRunDTO[]>(
    () => window.api.getWorkAnalyses(work.work_id, projectId),
    [work.work_id, projectId]
  )
  const owning = useMemo((): FactDTO | null => {
    if (!runs.data || !current) return null
    for (const r of runs.data) {
      const f = r.facts.find((x) => x.id === current.item.fact_id)
      if (f) return f
    }
    return null
  }, [runs.data, current])

  useEffect(() => {
    setCorrecting(false)
    setDraft('')
    setError(null)
  }, [current?.item.fact_id])

  const decide = useCallback(
    async (verdict: FactVerdictKind, correctedValue?: string): Promise<void> => {
      if (!current) return
      setBusy(true)
      setError(null)
      try {
        await window.api.recordFactVerdict({
          projectId,
          factId: current.item.fact_id,
          verdict,
          ...(verdict === 'corrected' ? { correctedValue: (correctedValue ?? '').trim() } : {})
        })
        setCorrecting(false)
        setDraft('')
        onDecided()
      } catch (e) {
        setError(e instanceof Error ? e.message : String(e))
      }
      setBusy(false)
    },
    [current, projectId, onDecided]
  )

  // Y / N / E answer the question; S moves on. Bare keys only — a modified key
  // belongs to the OS, and a shortcut must consume exactly the chord it claims.
  useEffect(() => {
    const onKey = (e: KeyboardEvent): void => {
      if (e.ctrlKey || e.metaKey || e.altKey) return
      const t = e.target as HTMLElement | null
      if (t && (t.tagName === 'INPUT' || t.tagName === 'TEXTAREA' || t.isContentEditable)) return
      if (!current || busy) return
      // U undoes a decision already made. Handled BEFORE the guard below, which
      // exists to stop a second verdict landing on a settled item — undo is the
      // one key that only makes sense once it IS settled.
      if (e.key.toLowerCase() === 'u' && current.item.verdict !== null) {
        e.preventDefault()
        void decide('unresolved')
        return
      }
      if (current.item.verdict !== null) return
      // The keys are the INITIALS of the words on the buttons. They were y/n/e
      // against Keep/Strike/Change — a second mapping to learn on a screen whose
      // whole point is not making the reader learn anything.
      const k = e.key.toLowerCase()
      if (k === 'r') {
        e.preventDefault()
        void decide('accepted')
      } else if (k === 'w') {
        e.preventDefault()
        void decide('rejected')
      } else if (k === 'f') {
        e.preventDefault()
        setCorrecting(true)
      } else if (k === 's') {
        e.preventDefault()
        const i = pending.findIndex((f) => f.item.fact_id === current.item.fact_id)
        if (pending.length > 1) setSelected(pending[(i + 1) % pending.length].item.fact_id)
      }
    }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [current, busy, pending, decide])

  /**
   * THE ROW HEADER IS A SCHEMA FIELD, NOT A WORD THIS SCREEN INVENTED.
   *
   * A reading is keyed by (subject, conditions), and in this corpus the subject
   * is also carried by a field the schema asked for — `Variant`. Printing a
   * made-up "reading" header beside that field showed `KE07 K222A` twice in
   * every row: once as our label for the group, once as the column's own value.
   * So the header borrows the first text field's label, and that field is then
   * dropped from the value columns — it is the row's name, not one of its
   * measurements.
   */
  // EVERY schema field is a column. The row header is `fact.subject` — which is
  // NOT any field's value: the corpus has `kcat` facts whose subject is `KE15`
  // beside a Variant field reading `KE15 D48A`, and facts whose subject is
  // simply `protein`. Borrowing a field's LABEL for it therefore printed one
  // thing under the name of another and dropped that field's real values from
  // the table entirely. The header is labelled for what it is.
  const fields = schema?.fields ?? []
  // A flagged fact with NO field link has no cell to sit in. Silently dropping
  // it left the sidebar promising "N to check" over a table that highlighted
  // nothing — 336 records in this corpus carry `field_id IS NULL`.
  const orphans = flags.filter((f) => f.fieldId === null || f.key === null)
  const flagAt = (fieldId: number, key: string): Flagged | undefined =>
    flags.find((f) => f.fieldId === fieldId && f.key === key)

  // Which readings are drawn. Flagged only by default — see the table comment.
  //
  // A flag on a PAPER-WIDE condition has a `key` of its own — the one reading
  // the fact happens to be stored against — but the value is drawn on every
  // reading it covers, so every one of them is a row someone must look at. Those
  // keys are added below, once `paperWide` is known.
  const flaggedKeys = useMemo(
    () => new Set(flags.map((f) => f.key).filter((k): k is string => k !== null)),
    [flags]
  )

  /**
   * A value stated ONCE for the whole paper — an assay temperature, a buffer, a
   * substrate — resolved to the single record that carries it.
   *
   * The extractor files these under a subject of its own invention ("all
   * designs"), and rendering that as a row put a line in the table that is not a
   * measurement of anything, whose every other cell then read "no value". These
   * are CONDITIONS: they hold for every reading, so they are shown on every
   * reading, and the row they arrived on is not drawn.
   */
  /**
   * A value that identifies the ROW, resolved for every reading of that subject.
   *
   * A reading is `subject|conditions`, so one variant measured against four
   * substrates is four readings — correctly, they are four measurements. But the
   * paper names that variant ONCE, and its mutations once, so those records sit
   * on whichever reading the extractor happened to file them under and the other
   * three showed "no value" in the columns that say what the row IS. On one
   * paper that was nine subjects fragmented into thirty-two rows, most of them
   * near-empty, and the table read as broken rather than as sparse.
   *
   * Keyed on the SUBJECT alone, so it fills only from a record about the same
   * thing. It is a fallback: a reading with its own value keeps it, and where
   * two readings of one subject genuinely differ, neither is overwritten.
   */
  const subjectWide = useMemo(() => {
    const out = new Map<number, Map<string, ExtractionRowDTO>>()
    for (const r of work.rows) {
      if (r.field_id == null) continue
      const subj = (r.subject ?? '').trim().toLowerCase()
      if (subj === '') continue
      const per = out.get(r.field_id) ?? new Map<string, ExtractionRowDTO>()
      if (!per.has(subj)) per.set(subj, r)
      out.set(r.field_id, per)
    }
    return out
  }, [work.rows])
  const subjectOf = (key: string): string => key.slice(0, key.indexOf('|'))

  /** Readings that carry NOTHING of their own — only paper-wide conditions. */
  const conditionOnly = useMemo(() => {
    const out = new Set<string>()
    for (const key of work.order) {
      let own = 0
      for (const f of schema?.fields ?? []) {
        if (work.cells.get(f.id)?.get(key) && !paperWide.has(f.id)) own++
      }
      if (own === 0) out.add(key)
    }
    return out
  }, [work, schema, paperWide])
  // A FLAGGED READING IS NEVER FILTERED AWAY.
  //
  // `conditionOnly` hides a reading that carries nothing but the conditions the
  // paper stated for everything — noise on a table whose point is the values.
  // Applied after the flag filter, it also hid the one reading the queue had
  // asked about: the sidebar said "1 of 32 readings need a look" over a table
  // with no rows in it, and there was nothing on screen to act on or to explain
  // the discrepancy. Whatever else it is, a reading someone must look at is the
  // one thing this table exists to show.
  // EVERY reading a flagged value is drawn on, not only the one it is stored
  // against. A flagged paper-wide condition fills each of them, so each is a row
  // someone must look at — and gathering them here is what keeps the count the
  // sidebar shows and the rows this table draws describing the same thing.
  const flaggedRows = useMemo(() => {
    const out = new Set(flaggedKeys)
    if (flags.some((f) => f.fieldId !== null && paperWide.has(f.fieldId))) {
      for (const k of work.order) out.add(k)
    }
    return out
  }, [flaggedKeys, flags, paperWide, work.order])
  const visible = (showAll ? work.order : work.order.filter((k) => flaggedRows.has(k))).filter(
    (k) => flaggedRows.has(k) || !conditionOnly.has(k)
  )
  const hiddenCount = work.order.length - visible.length

  return (
    <div className="rv-paper" data-testid={`review-paper-${work.work_id}`}>
      <div className="rv-paper-scroll">
      <button className="btn-link rv-paper-title" onClick={() => onOpenWork(work.work_id)}>
        <RichText text={work.work_title} />
      </button>
      <div className="rv-paper-sub">
        {/* FLAGGED READINGS, not flagged facts: one reading can carry two
            flagged cells, and counting facts against readings compared two
            different things in one sentence. */}
        {flaggedKeys.size} of {work.order.length} readings need a look
        {pending.length === 0 && flags.length > 0 ? ' · all judged' : ''}
        {/* They were never flagged — "settled" would claim they had been judged. */}
        {hiddenCount > 0 &&
          ` · ${hiddenCount} clean reading${hiddenCount === 1 ? '' : 's'} hidden`}
        <button
          type="button"
          className="rv-showall"
          aria-pressed={showAll}
          onClick={() => setShowAll((v) => !v)}
          data-testid="review-show-all"
        >
          {showAll ? 'Show only what needs a look' : 'Show every reading'}
        </button>
      </div>

      {/* THE PAPER'S TABLE — drawn once, never scrolled away from.
          FLAGGED READINGS ONLY by default. A paper here carries up to 30
          readings against 10 columns, and printing all of them buried the two
          that need a decision — and pushed the question itself below the fold.
          The clean ones are one click away, because they are the context that
          makes a flagged value judgeable, not something to hide for good. */}
      {/* tabIndex so the sideways scroll is reachable without a pointer. */}
      <div className="rv-tbl-wrap" tabIndex={0}>
        <table className="rv-tbl" data-testid="review-table">
          <thead>
            <tr>
              {fields.map((f, i) => (
                <th key={f.id} className={i === 0 ? 'rv-tbl-subj' : undefined}>
                  {f.label}
                  {f.unit && <u>{f.unit}</u>}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {visible.map((key) => {
              // A PAPER-WIDE CONDITION FLAGS EVERY ROW IT FILLS.
              //
              // One stored fact — the temperature, the buffer, the substrate the
              // paper states once — is drawn on every reading it covers, and the
              // cell renderer below already resolves it that way. This did not,
              // so a row whose only flagged value was such a condition counted as
              // unflagged: it was filtered out of the table while the sidebar
              // still counted it, and the queue promised a reading it never drew.
              // Judging one row of a shared value judges the fact for all of
              // them, which is correct — it is one fact.
              const rowFlags = fields
                .map((f) => flagAt(f.id, key) ?? (paperWide.has(f.id) ? flags.find((x) => x.fieldId === f.id) : undefined))
                .filter((x): x is Flagged => Boolean(x))
              const isFlagged = rowFlags.length > 0
              const isHere = Boolean(current && rowFlags.some((f) => f.item.fact_id === current.item.fact_id))
              const judged = rowFlags.every((f) => f.item.verdict !== null)
              return (
                <tr
                  key={key}
                  className={`${isFlagged ? 'is-flag' : 'is-ok'} ${isFlagged && judged ? 'is-judged' : ''}`}
                  aria-current={isHere ? 'true' : undefined}
                  tabIndex={isFlagged ? 0 : undefined}
                  data-testid={isFlagged ? `review-row-${rowFlags[0].item.fact_id}` : undefined}
                  onClick={
                    isFlagged
                      ? () =>
                          setSelected(
                            (rowFlags.find((f) => f.item.verdict === null) ?? rowFlags[0]).item
                              .fact_id
                          )
                      : undefined
                  }
                  onKeyDown={
                    isFlagged
                      ? (e) => {
                          if (e.key === 'Enter' || e.key === ' ') {
                            e.preventDefault()
                            setSelected(
                              (rowFlags.find((f) => f.item.verdict === null) ?? rowFlags[0]).item
                                .fact_id
                            )
                          }
                        }
                      : undefined
                  }
                  data-flags={rowFlags.length > 1 ? rowFlags.length : undefined}
                >
                  {/* The status dot rides the FIRST cell — the subject column is
                      gone: `fact.subject` and the schema's own Variant field
                      carry the same text here, so printing both showed every
                      row's name twice. */}
                  {fields.map((f, colIdx) => {
                    // A paper-wide condition fills this cell when the reading
                    // has none of its own — it is the same value, not a repeat.
                    const wide = paperWide.get(f.id) ?? null
                    // Own value first, then the same subject's (a row's identity
                    // does not change with the conditions it was measured under),
                    // then the paper's.
                    const hit =
                      work.cells.get(f.id)?.get(key) ??
                      subjectWide.get(f.id)?.get(subjectOf(key)) ??
                      wide
                    const flag =
                      flagAt(f.id, key) ??
                      (wide ? flags.find((x) => x.fieldId === f.id) ?? null : null)
                    const shown =
                      flag?.item.verdict?.corrected_value ??
                      hit?.value_text ??
                      (hit?.value_num != null ? String(hit.value_num) : null)
                    if (!flag) {
                      return (
                        <td key={f.id} className={colIdx === 0 ? 'rv-tbl-subj' : undefined}>
                          {colIdx === 0 && isFlagged && (
                            <span
                              className={`rv-dot ${
                                judged ? VERDICT[rowFlags[0].item.verdict!.verdict].cls : 'wait'
                              }`}
                              aria-hidden="true"
                            >
                              {judged
                                ? rowFlags[0].item.verdict!.verdict === 'rejected'
                                  ? '✕'
                                  : '✓'
                                : '●'}
                            </span>
                          )}
                          {shown ?? <span className="mono rv-tbl-nov">no value</span>}
                        </td>
                      )
                    }
                    // This cell's OWN verdict — not the row's. A paper-wide
                    // condition is flagged once and shown on every reading, so
                    // the row's flags do not describe it.
                    const v = flag.item.verdict
                    const isCur = current?.item.fact_id === flag.item.fact_id
                    return (
                      <td key={f.id} className={colIdx === 0 ? 'rv-tbl-subj' : undefined}>
                        {colIdx === 0 && isFlagged && (
                          <span
                            className={`rv-dot ${
                              judged ? VERDICT[rowFlags[0].item.verdict!.verdict].cls : 'wait'
                            }`}
                            aria-hidden="true"
                          >
                            {judged
                              ? rowFlags[0].item.verdict!.verdict === 'rejected'
                                ? '✕'
                                : '✓'
                              : '●'}
                          </span>
                        )}
                        {/* THE CELL is the target, not just the row: one
                            reading can carry several flagged cells, and a row
                            click could only ever open the first of them. */}
                        <button
                          type="button"
                          className={`rv-cell ${v ? VERDICT[v.verdict].cls : ''}`}
                          aria-current={isCur ? 'true' : undefined}
                          onClick={(e) => {
                            e.stopPropagation()
                            setSelected(flag.item.fact_id)
                          }}
                          data-testid={`review-cell-${flag.item.fact_id}`}
                        >
                          {shown ?? 'no value'}
                        </button>
                      </td>
                    )
                  })}
                </tr>
              )
            })}
          </tbody>
        </table>
      </div>

      {/* THE QUESTION for the selected cell.
          The note sits ABOVE the claim, in the text flow. As a fixed side
          column its width was set by the longest note ("The model's answer was
          malformed") while most rows carry a short one, so the body shifted
          sideways every time the selection changed. */}
      {orphans.length > 0 && (
        <div className="rv-orphans" data-testid="review-orphans">
          {orphans.length} flagged {orphans.length === 1 ? 'record' : 'records'} in this paper
          {orphans.length === 1 ? ' names' : ' name'} no column of this schema, so
          {orphans.length === 1 ? ' it has' : ' they have'} no cell above:{' '}
          {orphans.map((o) => o.item.predicate).join(', ')}. Open the paper to judge
          {orphans.length === 1 ? ' it' : ' them'}.
        </div>
      )}

      {current && (
        <div className="rv-q" data-testid="review-question">
          <div className="rv-q-body">
            {/* When one reading carries several flagged cells they are separate
                decisions, each with its own evidence — so they are switched
                between, not merged. Absent for the common single-flag case. */}
            {siblings.length > 1 && (
              <div className="rv-sibs" role="tablist" aria-label="Flagged values in this reading">
                {siblings.map((sib) => (
                  <button
                    key={sib.item.fact_id}
                    type="button"
                    role="tab"
                    className={`rv-sib ${
                      sib.item.fact_id === current.item.fact_id ? 'is-on' : ''
                    } ${sib.item.verdict ? 'is-done' : ''}`}
                    aria-selected={sib.item.fact_id === current.item.fact_id}
                    onClick={() => setSelected(sib.item.fact_id)}
                    data-testid={`review-sib-${sib.item.fact_id}`}
                  >
                    {sib.item.verdict && <span aria-hidden="true">✓ </span>}
                    {sib.item.predicate}
                  </button>
                ))}
              </div>
            )}
            <div className="rv-q-head">
            <div className="rv-q-note">{noteFor(current.item)}</div>
            <h3
              className={`rv-claim ${(current.item.value_text ?? '').length > 52 ? 'is-long' : ''}`}
            >
              {current.item.predicate} <span>is</span>{' '}
              {current.item.value_text ?? <span>no value recorded</span>}
            </h3>
            <p className="rv-why">{current.item.reason}</p>
            </div>

            {/* Picture and text in ONE frame. They are two renderings of the
                same page — what the model was SHOWN and what it READ — so when
                they disagree that difference is the finding, and a reader
                comparing them should not have to cross a boundary to do it. */}
            <div className="rv-crop-box">
              <CropView
                workId={work.work_id}
                value={current.item.value_text}
                quote={owning?.evidence?.quote ?? null}
              />
              {owning?.evidence && (
                <details className="rv-fold">
                  <summary>
                    the text the model read
                    {current.item.failed_checks.length > 0 ? ' · and what the check said' : ''}
                  </summary>
                  {owning.evidence.quote ? (
                    <div className="rv-raw mono">{owning.evidence.quote}</div>
                  ) : (
                    <div className="rv-raw-none">
                      No wording was stored for this value — open the paper to check it.
                    </div>
                  )}
                  {!owning.evidence.verbatim && owning.evidence.quote && (
                    <div className="rv-raw-warn">
                      This wording was not confirmed against the paper&rsquo;s text.
                    </div>
                  )}
                  {current.item.failed_checks.map((c) => (
                    <div className="rv-chk" key={c.id}>
                      <b>{c.label}</b>
                      <p>{c.reason}</p>
                      {c.model && <i className="mono">answered by {c.model}</i>}
                    </div>
                  ))}
                </details>
              )}
            </div>

            {runs.loading && <SkeletonRows rows={2} />}
          </div>
        </div>
      )}
      </div>

      {/* THE DECISION — a FOOTER, pinned to the bottom of the pane.
          It used to sit under the crop, so on a paper with many readings the
          answer was a long scroll away from the row that was clicked: the user
          selected a cell, then had to go looking for the buttons. Pinning it
          means the question scrolls and the answer never moves. */}
      {current && (
        <div className="rv-foot" data-testid="review-foot">
          <div className="rv-foot-in">
            {current.item.verdict ? (
              <div className="rv-settled" data-testid="review-settled">
                <div className="rv-settled-said">
                  {/* WHAT was decided, in a sentence. `Kept` alone named the
                      verdict without naming the value it applies to, so the row
                      read as a status code rather than a record of a decision. */}
                  <b className={`rv-settled-verb ${VERDICT[current.item.verdict.verdict].cls}`}>
                    {current.item.verdict.verdict === 'accepted'
                      ? 'You said this is right'
                      : current.item.verdict.verdict === 'rejected'
                        ? 'You said this is wrong'
                        : 'You corrected this'}
                  </b>
                  {current.item.verdict.corrected_value && (
                    <span className="rv-settled-new">
                      {current.item.value_text ?? 'no value'} → {current.item.verdict.corrected_value}
                    </span>
                  )}
                </div>
                <div className="rv-settled-who">
                  {current.item.verdict.reviewer}, {fmtTime(current.item.verdict.created_at)}
                </div>
                <button
                  className="btn btn-secondary rv-undo"
                  disabled={busy}
                  onClick={() => void decide('unresolved')}
                  data-testid="review-undo"
                  data-tip="Takes the decision back. Both it and the retraction stay on the record."
                >
                  Undo <u className="mono">U</u>
                </button>
              </div>
            ) : correcting ? (
              <div className="rv-fix">
                <input
                  className="rv-fix-input"
                  value={draft}
                  autoFocus
                  placeholder={`the ${current.item.predicate} it should be`}
                  onChange={(e) => setDraft(e.target.value)}
                  onKeyDown={(e) => {
                    // Enter commits, Escape backs out. Both are stopped here so
                    // they cannot also reach the screen-level handler — Escape
                    // in particular is the browser's "leave this field" key and
                    // an unhandled one just blurs, leaving the composer open
                    // with no way back but the mouse.
                    if (e.key === 'Enter' && draft.trim()) {
                      e.preventDefault()
                      e.stopPropagation()
                      void decide('corrected', draft)
                    } else if (e.key === 'Escape') {
                      e.preventDefault()
                      e.stopPropagation()
                      setCorrecting(false)
                      setDraft('')
                    }
                  }}
                  data-testid="review-fix-input"
                />
                <button
                  className="btn btn-primary"
                  disabled={busy || draft.trim().length === 0}
                  onClick={() => void decide('corrected', draft)}
                  data-tip={
                    busy
                      ? 'Recording your decision…'
                      : draft.trim().length === 0
                        ? 'Type the value it should be first.'
                        : undefined
                  }
                  data-testid="review-fix-save"
                >
                  Save
                </button>
                <button className="btn btn-secondary" onClick={() => setCorrecting(false)}>
                  Cancel
                </button>
              </div>
            ) : (
              <div className="rv-answers">
                <button
                  className="btn rv-a rv-a-keep"
                  data-busy={busy || undefined}
                  disabled={busy}
                  data-tip={busy ? 'Recording your decision…' : undefined}
                  onClick={() => void decide('accepted')}
                  data-testid="review-keep"
                >
                  Looks right <u className="mono">R</u>
                </button>
                <button
                  className="btn rv-a rv-a-strike"
                  data-busy={busy || undefined}
                  disabled={busy}
                  data-tip={busy ? 'Recording your decision…' : undefined}
                  onClick={() => void decide('rejected')}
                  data-testid="review-strike"
                >
                  Looks wrong <u className="mono">W</u>
                </button>
                <button
                  className="btn rv-a rv-a-change"
                  data-busy={busy || undefined}
                  disabled={busy}
                  data-tip={busy ? 'Recording your decision…' : undefined}
                  onClick={() => setCorrecting(true)}
                  data-testid="review-change"
                >
                  Fix the value <u className="mono">F</u>
                </button>
                {pending.length > 1 && (
                  <button
                    className="rv-later"
                    onClick={() => {
                      const i = pending.findIndex((f) => f.item.fact_id === current.item.fact_id)
                      setSelected(pending[(i + 1) % pending.length].item.fact_id)
                    }}
                  >
                    Skip <u className="mono">S</u>
                  </button>
                )}
              </div>
            )}
            {error && (
              <div className="rv-err" role="alert" data-testid="review-error">
                Not recorded — {error}
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  )
}

// ---------------------------------------------------------------- screen
export function ReviewScreen({
  projectId,
  onOpenWork,
  focusFactId,
  onAddPapers
}: {
  projectId: number
  onOpenWork: (id: number) => void
  onAddPapers: () => void
  focusFactId?: number
}): JSX.Element {
  const queue = useAsync<ReviewItemDTO[]>(() => window.api.getReviewQueue(projectId), [projectId])
  const rows = useAsync<ExtractionRowDTO[]>(() => window.api.getExtractionRows(projectId), [projectId])
  const schemas = useAsync<ExtractionSchemaDTO[]>(() => window.api.listSchemas(), [])
  const project = useAsync(() => window.api.getProject(projectId), [projectId])
  const [paper, setPaper] = useState<number | null>(null)

  const reload = useCallback(() => {
    queue.reload()
    rows.reload()
  }, [queue.reload, rows.reload])

  // Papers that have something to look at, each with its readings and the cells
  // the queue flagged. A fact is placed by matching its id against the extraction
  // rows — ReviewItemDTO carries no field or subject of its own.
  const papers = useMemo(() => {
    if (!queue.data || !rows.data) return []
    const byFact = new Map<number, ExtractionRowDTO>()
    for (const r of rows.data) if (!byFact.has(r.fact_id)) byFact.set(r.fact_id, r)
    const grouped = groupReadings(rows.data)
    const out: { work: WorkReadings; schemaId: number | null; flags: Flagged[] }[] = []
    for (const w of grouped) {
      const flags: Flagged[] = []
      for (const it of queue.data) {
        if (it.work_id !== w.work_id) continue
        const row = byFact.get(it.fact_id)
        flags.push({
          item: it,
          fieldId: row?.field_id ?? null,
          key: row ? readingKey(row) : null
        })
      }
      if (flags.length > 0) {
        // ONE ENTRY PER SCHEMA THE PAPER WAS READ AGAINST.
        //
        // A paper is read against every schema the project attaches, so its
        // records span several and one table cannot hold them: the columns of a
        // kinetics schema have no cell for a melting temperature. Drawing the
        // first schema found rendered the flagged reading of another as a row of
        // "no value", and the readings flagged in the schema NOT drawn were
        // unreachable while still being counted — a queue promising work with no
        // way to reach it. Split here, and the tabs above the table pick between
        // them; a paper read against one schema has one tab and looks unchanged.
        const bySchema = new Map<number | null, Flagged[]>()
        for (const f of flags) {
          const sid = byFact.get(f.item.fact_id)?.schema_id ?? null
          const l = bySchema.get(sid)
          if (l) l.push(f)
          else bySchema.set(sid, [f])
        }
        for (const [sid, list] of bySchema) {
          out.push({
            work: w,
            schemaId: sid ?? w.rows.find((r) => r.schema_id != null)?.schema_id ?? null,
            flags: list
          })
        }
      }
    }
    return out
  }, [queue.data, rows.data])

  // Arriving with a fact in hand (an Extraction status chip): open its paper.
  const honoured = useRef<number | null>(null)
  useEffect(() => {
    if (focusFactId === undefined || honoured.current === focusFactId || papers.length === 0) return
    const p = papers.find((x) => x.flags.some((f) => f.item.fact_id === focusFactId))
    honoured.current = focusFactId
    if (p) setPaper(p.work.work_id)
  }, [focusFactId, papers])

  // A paper may have flagged readings under SEVERAL schemas, and each needs its
  // own table — the columns of one have no cell for the other's quantities. The
  // sidebar stays per-paper; the schema is chosen by the tabs above the table.
  const activePaperId = papers.find((p) => p.work.work_id === paper)?.work.work_id ?? papers[0]?.work.work_id ?? null
  const forPaper = useMemo(
    () => papers.filter((p) => p.work.work_id === activePaperId),
    [papers, activePaperId]
  )
  const [schemaTab, setSchemaTab] = useState<number | null>(null)
  // The chosen tab, or the first — reset by falling through whenever the paper
  // changes and the remembered schema is not one this paper has.
  const active =
    forPaper.find((p) => p.schemaId === schemaTab) ?? forPaper[0] ?? null

  return (
    <div className="screen screen-review" data-testid="screen-review">
      <DataView
        state={queue}
        isEmpty={(d) => d.length === 0}
        empty={
          project.data && project.data.extracted_count === 0 ? (
            <EmptyState
              title="Nothing has been extracted yet."
              hint={
                project.data.work_count === 0
                  ? 'This queue holds claims a model made about your papers that it was not sure of.'
                  : 'Run an extraction and anything uncertain lands here.'
              }
              testid="review-empty"
            >
              {project.data.work_count === 0 && (
                <div className="empty-state-actions">
                  <button
                    type="button"
                    className="btn btn-primary"
                    data-testid="review-empty-add-papers"
                    onClick={onAddPapers}
                  >
                    Add papers
                  </button>
                </div>
              )}
            </EmptyState>
          ) : (
            <EmptyState
              title="Nothing needs review."
              hint="Every extracted claim passed its checks."
              testid="review-empty"
            />
          )
        }
      >
        {() => (
          <div className="rv-split">
            <div className="rv-papers" data-testid="review-papers">
              <div className="mono rv-papers-lab">Papers to check</div>
              {rows.error && <ErrorState error={rows.error} onRetry={rows.reload} />}
              {/* ONE ENTRY PER PAPER, whatever it was read against. `papers`
                  holds a (paper, schema) pair each, so the counts of a paper's
                  schemas are summed here — a sidebar that listed the same title
                  twice would read as two papers. The schema is chosen by the
                  tabs above the table. */}
              {[...new Map(papers.map((p) => [p.work.work_id, p])).values()].map((p) => {
                const mine = papers.filter((x) => x.work.work_id === p.work.work_id)
                const flagCount = mine.reduce((n, x) => n + x.flags.length, 0)
                const open = mine.reduce(
                  (n, x) => n + x.flags.filter((f) => f.item.verdict === null).length,
                  0
                )
                return (
                  <button
                    key={p.work.work_id}
                    className="rv-pp"
                    aria-current={active?.work.work_id === p.work.work_id ? 'true' : undefined}
                    onClick={() => {
                      setPaper(p.work.work_id)
                      setSchemaTab(null)
                    }}
                    data-testid={`review-paper-tab-${p.work.work_id}`}
                  >
                    <span className="rv-pp-t"><RichText text={p.work.work_title} /></span>
                    <span className="rv-pp-m">
                      <span className={`rv-pp-n ${open === 0 ? 'is-done' : ''}`}>
                        {open === 0 ? `all ${flagCount} judged` : `${open} to check`}
                      </span>
                      <span className="mono">{p.work.order.length} readings</span>
                    </span>
                  </button>
                )
              })}
            </div>

            <div className="rv-stage">
              {/* HARD RULE 0.6: shown only when there is a choice to make. A
                  paper read against one schema has nothing to switch between,
                  and a lone tab would be a control that does nothing. */}
              {forPaper.length > 1 && (
                <div className="rv-schematabs" role="tablist" aria-label="Schema">
                  {forPaper.map((p) => {
                    const open = p.flags.filter((f) => f.item.verdict === null).length
                    const name =
                      schemas.data?.find((s) => s.id === p.schemaId)?.name ?? 'Unassigned'
                    return (
                      <button
                        key={p.schemaId ?? 'none'}
                        role="tab"
                        className="rv-schematab"
                        aria-selected={active?.schemaId === p.schemaId}
                        onClick={() => setSchemaTab(p.schemaId)}
                        data-testid={`review-schema-tab-${p.schemaId ?? 'none'}`}
                      >
                        {name}
                        <span className={`rv-schematab-n ${open === 0 ? 'is-done' : ''}`}>
                          {open === 0 ? p.flags.length : open}
                        </span>
                      </button>
                    )
                  })}
                </div>
              )}
              {active ? (
                <PaperReview
                  key={`${active.work.work_id}-${active.schemaId ?? 'none'}`}
                  work={active.work}
                  // NO fallback to schemas[0]: a paper extracted under
                  // Thermostability would have been drawn with Kinetics columns,
                  // labelling its values as quantities nobody measured.
                  schema={schemas.data?.find((s) => s.id === active.schemaId) ?? null}
                  flags={active.flags}
                  projectId={projectId}
                  onOpenWork={onOpenWork}
                  onDecided={reload}
                />
              ) : (
                <div className="rv-missing">Select a paper to review its extractions.</div>
              )}
            </div>
          </div>
        )}
      </DataView>
    </div>
  )
}
