// Drive the seeded corpus through the REAL pipeline against the REAL gateway,
// then mark everything it produced as a SHIPPED analysis.
//
//   npm run corpus:process              # finish the default DB, runs stay 'local'
//   npm run corpus:process -- --ship    # …and stamp them for the shipped export
//   CORPUS_DB_PATH=… npm run corpus:process
//
// This is the only thing allowed to create analyses that ship with the app, and
// it creates them the same way a user's machine would: the same `Scheduler`, the
// same `HostPool`, the same `plan()`, the same stages, the same provider. The
// only difference is the last step, which restamps `run_origin` — see below.
//
// WHY A PRECOMPUTED CORPUS AT ALL.
//
// A full run over 20 papers costs ~19 minutes of wall clock and ~160k tokens
// against a gateway most installs will not have configured. Making that the
// price of seeing the app do anything is not a defensible first-run experience,
// and the alternative — showing an empty app and a progress bar for twenty
// minutes — teaches the user nothing about what the app is for.
//
// WHY THAT IS NOT A RETURN OF THE MOCK.
//
// Every row this produces was generated by `claude-haiku-4-5` reading the actual
// PDF. The facts are the model's, the quotes are the paper's, the provenance is
// real and re-derivable. What ships is a RECORDING of a genuine run, not a
// fabrication of one — and `run_origin = 'shipped'` says so in the data, is
// carried on the DTO, and is rendered on the provenance card, so a reader is
// never left to assume their own machine computed it. A user who re-runs any
// paper gets a `'local'` run that supersedes it by the normal path.

import { existsSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { randomUUID } from 'node:crypto'
import { initDatabase, type DB } from '../src/main/db/connection'
import { defaultDbPath } from '../src/main/db/paths'
import { CommunicatorLlmProvider, UnavailableLlmProvider } from '../src/main/llm/provider'
import { selectProvider } from '../src/main/llm/select'
import { LLM_GATE } from '../src/main/pipeline/gate/llmGate'
import { VectorSearch } from '../src/main/search/vectorSearch'
import { HostPool } from '../src/main/pipeline/host/pool'
import { Scheduler } from '../src/main/pipeline/scheduler'
import { STAGES } from '../src/main/pipeline/stages'
import { resolveRegistry } from '../src/main/pipeline/registry'

const sleep = (ms: number): Promise<void> => new Promise((r) => setTimeout(r, ms))
const log = (s: string): void => {
  // eslint-disable-next-line no-console
  console.log(s)
}

export async function processCorpus(): Promise<void> {
  const dbPath = process.env.CORPUS_DB_PATH ?? defaultDbPath()
  if (!existsSync(dbPath)) {
    throw new Error(`no database at ${dbPath} — run \`npm run seed:fresh\` first`)
  }
  const db: DB = initDatabase(dbPath)

  // ---- the provider, and a REFUSAL to proceed without one -----------------
  //
  // `mode: 'live'` rather than the default. This script exists to produce runs
  // that will be shipped and shown to people who cannot check them; starting it
  // without a model and discovering that twenty papers later is the failure
  // mode that matters most here, so it declines to start at all.
  const selection = await selectProvider({ mode: 'live' })
  const provider = selection.provider
  if (provider instanceof UnavailableLlmProvider) {
    throw new Error(`refusing to process the corpus: ${provider.why}`)
  }
  log(`provider: ${provider.name} (${provider.model}) — ${selection.reason}`)

  const entryPath = join(process.cwd(), 'out', 'main', 'stageHost.js')
  if (!existsSync(entryPath)) {
    throw new Error(`host entry missing: ${entryPath} (run \`npm run build\`)`)
  }
  const runDir = join(dirname(dbPath), 'run')
  mkdirSync(runDir, { recursive: true })
  const hostPool = new HostPool({ entryPath, runDir, instanceId: randomUUID() })

  const registry = resolveRegistry(STAGES)
  log(`stages: ${registry.order.map((r) => r.stage.id).join(' -> ')}`)

  // SEMANTIC SEARCH, wired exactly as the app wires it.
  //
  // Without it `ctx.semantic` is null and verify-citations refuses every run
  // with "semantic search is not available in this build" — so the one stage
  // that checks a citation against the CITED paper could never run here, and
  // a corpus processed by this script was silently missing the half of the
  // feature the user asked for. The verdicts in the database had all come from
  // the GUI; this script has never produced one.
  const vectorSearch = new VectorSearch(dbPath)
  const sched = new Scheduler(db, provider, {
    concurrency: 2,
    idleMs: 50,
    hostPool,
    semantic: async (text, k, workIds) => {
      const res = await vectorSearch.query(text, k, workIds)
      return { blocks: res.hits, spaceId: res.spaceId, strategy: res.strategy }
    }
  })

  const docs = db
    .prepare('SELECT id, work_id FROM document ORDER BY work_id')
    .all() as Array<{ id: number; work_id: number }>
  const projectId = (
    db.prepare('SELECT MIN(id) AS id FROM project').get() as { id: number | null }
  ).id
  if (projectId == null) throw new Error('the database has no project to process against')

  let planned = 0
  for (const d of docs) planned += sched.plan({ workId: d.work_id, documentId: d.id, projectId }).length
  log(`planned ${planned} job(s) across ${docs.length} document(s)`)

  LLM_GATE.resetStats()
  const t0 = Date.now()
  sched.start()

  const budgetMs = Number(process.env.CORPUS_BUDGET_MS ?? 60 * 60 * 1000)
  const deadline = Date.now() + budgetMs
  let lastReport = 0
  while (Date.now() < deadline) {
    const live = (
      db
        .prepare(
          `SELECT COUNT(*) AS c FROM processing_job WHERE status IN ('queued','running','blocked')`
        )
        .get() as { c: number }
    ).c
    if (live === 0 && sched.inFlightCount() === 0) break
    if (Date.now() - lastReport > 20_000) {
      lastReport = Date.now()
      const done = (
        db.prepare(`SELECT COUNT(*) AS c FROM processing_job WHERE status='done'`).get() as {
          c: number
        }
      ).c
      log(`  … ${done} done, ${live} live, gate peak ${LLM_GATE.peak()}`)
    }
    await sleep(250)
  }
  sched.stop()
  await sleep(300)
  // Guarded, and the report below runs either way. A host that fails to shut
  // down cleanly must not cost us the account of what the batch produced —
  // that is the entire output of a run that may have taken twenty minutes.
  try {
    hostPool.shutdown()
  } catch (err) {
    log(`host pool shutdown: ${(err as Error).message}`)
  }

  // What is LEFT, stated plainly. A run that stopped on its budget with jobs
  // still queued is a partial run, and reporting only what finished would let
  // an incomplete corpus be exported as if it were whole.
  const outstanding = (
    db
      .prepare(
        `SELECT COUNT(*) AS c FROM processing_job WHERE status IN ('queued','running','blocked')`
      )
      .get() as { c: number }
  ).c
  if (outstanding > 0) {
    log(`\nINCOMPLETE: ${outstanding} job(s) still outstanding — re-run to continue.`)
  }

  // ---- attribution ---------------------------------------------------------
  //
  // Restamped only AFTER the run, and only over rows this process created, so a
  // pre-existing local analysis in the same database is never relabelled as
  // something the project shipped. The note records WHICH model and WHEN, which
  // is what a reader needs to judge whether a shipped result is still current.
  //
  // ONLY when this run is destined for the export. The same driver is the right
  // way to finish processing a real machine's corpus — a seeded install whose
  // `citation-contexts` has never run holds analyses but no roles, because a
  // role names a sentence at an offset in a PDF that only the stage can read.
  // Stamping THAT run `shipped` would tell its owner the project precomputed
  // rows their own machine had just spent twenty minutes producing, which is
  // the inverse of the lie `run_origin` exists to prevent. So the stamp is opt
  // in, and the default leaves the pipeline's own honest `local`.
  const forExport = process.argv.includes('--ship') || process.env.CORPUS_SHIP === '1'
  const stampedAt = new Date().toISOString()
  const note = `Precomputed with ${provider.model} on ${stampedAt.slice(0, 10)} and distributed with the app.`
  const stamped = forExport
    ? db
        .prepare(
          `UPDATE analysis_run
              SET run_origin = 'shipped', origin_note = ?
            WHERE run_origin = 'local' AND created_at >= ?`
        )
        .run(note, new Date(t0).toISOString())
    : { changes: 0 }

  const count = (sql: string): number =>
    (db.prepare(sql).get() as { c: number } | undefined)?.c ?? -1

  const roleRows = db
    .prepare(
      `SELECT role_source, COUNT(*) AS c FROM citation_context
        WHERE role_source IS NOT NULL GROUP BY role_source`
    )
    .all() as Array<{ role_source: string; c: number }>

  log('\n=== what a real model produced ===')
  log(`  wall clock            ${((Date.now() - t0) / 1000).toFixed(1)}s`)
  log(`  gate peak in flight   ${LLM_GATE.peak()}`)
  if (provider instanceof CommunicatorLlmProvider) {
    log(`  LLM calls             ${provider.totals.calls}`)
    log(`  tokens                ${provider.totals.totalTokens}`)
  }
  log(`  analysis_run          ${count('SELECT COUNT(*) AS c FROM analysis_run')}`)
  log(
    forExport
      ? `  …stamped shipped      ${stamped.changes}`
      : `  …left run_origin      local (pass --ship to mark these for export)`
  )
  log(`  fact                  ${count('SELECT COUNT(*) AS c FROM fact')}`)
  log(`  evidence_span         ${count('SELECT COUNT(*) AS c FROM evidence_span')}`)
  log(`  measurement           ${count('SELECT COUNT(*) AS c FROM measurement')}`)
  log(`  fold_improvement      ${count('SELECT COUNT(*) AS c FROM fold_improvement')}`)
  log(`  citation_edge         ${count('SELECT COUNT(*) AS c FROM citation_edge')}`)
  log(`  citation_context      ${count('SELECT COUNT(*) AS c FROM citation_context')}`)
  for (const r of roleRows) log(`  …role by ${r.role_source.padEnd(6)}      ${r.c}`)
  log(
    `  …unclassified         ${count('SELECT COUNT(*) AS c FROM citation_context WHERE role_source IS NULL')}`
  )
}

if (require.main === module) {
  processCorpus().then(
    () => process.exit(0),
    (err) => {
      // eslint-disable-next-line no-console
      console.error(String((err as Error)?.message ?? err))
      process.exit(1)
    }
  )
}
