// TEST-ONLY pagination fixture. NOT a corpus, and never shipped.
//
// The Extraction screen's UNASSIGNED bucket is the last surface rendering a flat
// record table, so it is the only one that paginates (PAGE_SIZE 40). Exercising
// that needs more than two pages of records, and quantity is the ONLY property
// the test cares about — it counts rows and clicks "Show more".
//
// So the records are attached to a SYNTHETIC work of this fixture's own making,
// never to one of the 20 real papers. They used to hang off work 5 (Privett
// 2012, a real paper by real authors) with `provider = 'mock-provider'` and
// invented units — 95 measurements the Extraction screen presented as readings
// taken from that paper. A pagination test does not need, and is not entitled
// to, claims about a real publication.
//
// Everything here is self-labelling: the work is titled as a fixture, the run's
// provider names this script, and `run_origin` is 'imported' because no model
// produced it and 'local' would assert that one did.
//
//   ELECTRON_RUN_AS_NODE=1 electron --import tsx scripts/seed-extraction-bulk.ts
//
// Honors CORPUS_DB_PATH (always fresh — the DB is recreated).

import { existsSync, mkdirSync, rmSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { initDatabase, setDb, closeDb, type DB } from '../src/main/db/connection'
import { seed } from '../src/main/db/seed'

/** How many unassigned records to create. > 2 pages so "Show more" is meaningful. */
const N_RECORDS = Number(process.env.EXTRACTION_BULK_RECORDS ?? 95)
const NOW = process.env.CORPUS_FAKE_NOW ?? '2026-01-01T00:00:00Z'
export const BULK_PROJECT_ID = 1
/** Names itself, in every list it can appear in. */
const BULK_WORK_TITLE = 'PAGINATION FIXTURE — not a real paper, not a real reading'

function dbPath(): string {
  const base = process.env.CORPUS_DB_PATH
  if (base && base.trim()) return base
  return join(process.cwd(), '.corpus-data', 'corpus-extraction-bulk.sqlite')
}

function seedBulk(db: DB): void {
  const now = NOW
  seed(db, { now })

  const run = db.transaction(() => {
    // A work of this fixture's own, so no real paper is described.
    const workId = Number(
      db
        .prepare(
          `INSERT INTO work (title, work_type, created_at, updated_at)
           VALUES (@title, 'other', @now, @now)`
        )
        .run({ title: BULK_WORK_TITLE, now }).lastInsertRowid
    )
    db.prepare(
      `INSERT INTO project_work
         (project_id, work_id, relevance, expansion_priority, inclusion_status, reviewed, created_at, updated_at)
       VALUES (@pid, @wid, 0, 0, 'unread', 0, @now, @now)`
    ).run({ pid: BULK_PROJECT_ID, wid: workId, now })

    const runId = Number(
      db
        .prepare(
          `INSERT INTO analysis_run
             (work_id, project_id, analysis_type, model, provider, prompt_version, schema_version,
              run_timestamp, verifier_result, deterministic_validation, superseded,
              doc_input_hash, run_origin, origin_note, created_at)
           -- 'not-run' and validation 0, because nothing ran and nothing was
           -- validated. The old row claimed 'passed', which is an assertion
           -- about a model's output when there was no model and no output.
           VALUES (@wid, @pid, 'measurement', 'none', 'pagination-fixture', 'v1', 's1', @now,
                   'not-run', 0, 0, 'bulk-unassigned', 'imported',
                   'Synthetic rows generated by scripts/seed-extraction-bulk.ts to exercise pagination. No model produced these.',
                   @now)`
        )
        .run({ wid: workId, pid: BULK_PROJECT_ID, now }).lastInsertRowid
    )

    const insFact = db.prepare(
      `INSERT INTO fact (analysis_run_id, kind, predicate, value_text, created_at)
       VALUES (@run, 'directly-reported', 'fixture-row', @value, @now)`
    )
    // field_id omitted -> NULL -> the record is genuinely unassigned.
    //
    // No unit and no conditions. The quantity counts; the old `s^-1` at
    // `pH 7.0, 25C` was assay detail invented to look plausible, and plausible
    // is exactly what a fabrication should not be.
    const insMeas = db.prepare(
      `INSERT INTO measurement (fact_id, quantity, value_num, created_at)
       VALUES (@fid, @quantity, @value, @now)`
    )
    for (let i = 0; i < N_RECORDS; i++) {
      const fid = Number(
        insFact.run({ run: runId, value: `fixture row ${i}`, now }).lastInsertRowid
      )
      insMeas.run({ fid, quantity: `fixture quantity ${i}`, value: i + 1, now })
    }
  })
  run()
}

function main(): void {
  const p = dbPath()
  mkdirSync(dirname(p), { recursive: true })
  for (const suffix of ['', '-wal', '-shm']) {
    const f = p + suffix
    if (existsSync(f)) rmSync(f)
  }
  const db = initDatabase(p)
  setDb(db)
  seedBulk(db)
  closeDb()
  // eslint-disable-next-line no-console
  console.log(`[seed-extraction-bulk] ok -> ${p} (unassigned records=${N_RECORDS})`)
}

main()
